---
title: "Cluster Analysis"
output: github_document
editor_options: 
  chunk_output_type: console
---

# Cluster

```{r}
library(tidyverse)
library(readr)
library(janitor)
library(factoextra)
library(stats)
ff_data <- read_csv("data/ff_2020.csv")

ff_data <- as.data.frame(ff_data)

row.names(ff_data) <- ff_data$player_name
```


## Scale Data

```{r}
ff_scale <- ff_data %>%
  select(tgt, yac, ybc, ppr)

ff_scale <- scale(ff_scale)
ff_scale <- na.omit(ff_scale)
```

```{r}
distance <- get_dist(ff_scale)
fviz_dist(distance, gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

# Determining Optimal Clusters

## Elbow method

```{r}
fviz_nbclust(ff_scale, kmeans, method = "wss")
```

From the elbow method, it looks like k=3 will be the optimal value.

```{r}
final <- kmeans(ff_scale, centers = 3, nstart = 25)
finalplot <- fviz_cluster(final, data = ff_scale, labelsize = 7) + ggtitle("k = 3") 
finalplot
```

# Run algorithm

```{r}
# compute k-means with k=2
set.seed(1234)
k3 <- kmeans(ff_scale, centers = 3, nstart = 25)

# Print the results
print(k3)
```

We get clusters of 80, 41, 16

We want between_SS / total_SS to approach 1 so 74.1%.
  
# Put clusters into the dataframe

This will make it easier on draft day to see which players are in the same cluster.

```{r}
ff_scale <- as.data.frame(ff_scale)

ff_scale$player <- rownames(ff_scale)

ff_scale$clusters3 <- as.factor(k3$cluster)
```

